### ISSUE TITLE
Fill arrow not functioning

### ISSUE THREAD

**Issue by dreeves4321** [goinvo/staffplan-next-app#240] opened 2024-10-16 13:27 UTC
Fill arrow on plan hours is not working. 
When I click the fill arrow, nothing happens.
My expectation is it fills hours to the project end date. If there is no end date, it fills "forever" (or till some reasonable benchmark like the end of the year)

**Comment by jsonin** [comment] 2024-10-16 14:41
Can confirm the fill forward is no longer working.
If there is an end date, the fill forward fills until that date.
If there is not an end date (as part of the project meta data), then the fill forward fills until the end of the current view state (last remaining viewable week) of the screen.

**Comment by jen-p** [comment] 2024-10-16 17:18
Another weird fill arrow behavior... it appears to be filling backwards and not forwards?


https://github.com/user-attachments/assets/68d8140b-114f-4f82-8687-8a77e163ebb9

**Comment by jen-p** [comment] 2024-10-16 17:34
But that shouldn't be the user experience we expect people who aren't internal to us to have to do to see the right thing. Is there a way we can make it so we don't have to reload and click multiple times to get the correct behavior?

And besides, I tried the reload second click and it's just not filling forwards at all for those later dates.

**Comment by fermion** [comment] 2024-10-16 17:43
I realize this is frustrating for you, ideally this would be working as you're expecting.

> But that shouldn't be the user experience we expect people who aren't internal to us to have to do to see the right thing

Agreed, and I apologize if my hand waving explanation above made you think I was suggesting users should need to fully refresh the page in order to see the correct data. This is a bug and should be fixed, I'm simply commenting on what you're sharing with the screen recordings for @HankC138 or @zhukovdigital or whoever else might pick this up 👍🏻 

Again, I know this is frustrating when things don't work as you expect. Ideally with bug reports you'll do what you've done and capture the issue in screenshots or a recording. I think you've uncovered multiple issues here so we may need to narrow the scope of this issue and create others to capture all that's currently broken.

**Comment by HankC138** [comment] 2024-10-16 18:38
> > Another weird fill arrow behavior... it appears to be filling backwards and not forwards?
> > Screenshare.-.2024-10-16.1_17_21.PM.mp4
> 
> I think what's happening here is that the UI is updating the inputs/values with the local data on the first click. The second click replaces that with the response from the server (my guess is the deletion may be broken).
> 
> Try to click/fill once, then reload the page fully. I bet you'll see what you're seeing after the second click.

Did the behavior in the video also happen for you @fermion ? When I try and replicate it the arrow is working as intended.

**Comment by HankC138** [comment] 2024-10-16 18:47
I think what may be happening is due to assignment start/end dates. Currently there's no way to edit an existing assignment or see what that assignments start and end dates are after it has been created and that can certainly cause some confusion when entering time or trying to use the fill function. Is there an idea of how/where we might want to display those dates if they exist and perhaps how we might want to edit an existing assignment?

**Comment by fermion** [comment] 2024-10-16 18:50
> > > Another weird fill arrow behavior... it appears to be filling backwards and not forwards?
> > > Screenshare.-.2024-10-16.1_17_21.PM.mp4
> > 
> > 
> > I think what's happening here is that the UI is updating the inputs/values with the local data on the first click. The second click replaces that with the response from the server (my guess is the deletion may be broken).
> > Try to click/fill once, then reload the page fully. I bet you'll see what you're seeing after the second click.
> 
> Did the behavior in the video also happen for you @fermion ? When I try and replicate it the arrow is working as intended.

I didn't attempt to repro this one.

**Comment by dreeves4321** [comment] 2024-10-16 18:59
The fill forward should fill to the project end date. The assignment end
date should change with it if necessary.

**Comment by fermion** [comment] 2024-10-16 19:06
> The assignment end date should change with it if necessary

Not sure I agree here. It doesn't really make sense, at least not without changing the assignment UI.

IMO the end date should be called out more clearly in the UI for an assignment, that may help make it more clear to users what's going on when the inputs don't fill past the end date.

Clicking an input cell that's not in the bounds of the assignment start/end date shouldn't show the fill button. It should prompt the user to set this as the start/end date.

**Comment by HankC138** [comment] 2024-10-16 19:07
> > The assignment end date should change with it if necessary
> 
> Not sure I agree here. It doesn't really make sense, at least not without changing the assignment UI.
> 
> IMO the end date should be called out more clearly in the UI for an assignment, that may help make it more clear to users what's going on when the inputs don't fill past the end date.
> 
> Clicking an input cell that's not in the bounds of the assignment start/end date shouldn't show the fill button. It should prompt the user to set this as the start/end date.

I agree with this

**Comment by dreeves4321** [comment] 2024-10-16 21:44
I’d like to hear juhan and Jen’s opinion. Currently the user experience is pretty divorced from any notion of an assignment end date and start date. They’re been de-emphasized and requiring the user to maintain them would only cause confusion. On Oct 16, 2024, at 3:07 PM, Corbin Campbell ***@***.***> wrote:﻿


The assignment end date should change with it if necessary

Not sure I agree here. It doesn't really make sense, at least not without changing the assignment UI.
IMO the end date should be called out more clearly in the UI for an assignment, that may help make it more clear to users what's going on when the inputs don't fill past the end date.
Clicking an input cell that's not in the bounds of the assignment start/end date shouldn't show the fill button. It should prompt the user to set this as the start/end date.

I agree with this

**Comment by jsonin** [comment] 2024-10-16 21:54
Open ended fill = needed.
Fill-to-end-of-project, if an end date has been put in, = needed.

A visual signal on the timeline, marking the column/week that the project ends (at least in terms of the contract or the desirement),
and/or
the act of marking the end of the project in the visual timeline (along with the option to update it in the edit-project-metadata) = needed.

The current fill function, fill every cell in view, is a fine v.01.
We need to work Fill v.02... a solid idea + UI design now, and implement after we get through this current round of bugs to ship a basic StaffPlan to the public. 

Note: we'll still be able to overshoot, overcharge, a formalized end date. It's a marker for "that's where we need to end" and to help with math (how much are we over/under charging, etc).

**Comment by fermion** [comment] 2024-10-16 23:39
> Open ended fill = needed

Why is this needed? Is the use case someone like Jon Follett who's on BD 20 hours/week permanently? If so then I think that we need to introduce a new concept, some variation on an assignment that's functions differently from the current assignments attached to projects and whose work weeks know how to populate themselves. The idea being:

1. one of these new assignment types is created
2. a weekly estimated hours is set on creation to auto fill in for all weeks
3. the UI renders the amount of hours in the past/future inputs by default for estimated hours
    * if a value is changed, then a work week is created for that week to store the different value
    * when an actual value is set for a work week it causes a work week to be created and saved for this

I think this would solve the use case for Jon. I'm just not convinced that an open fill for all of time into the future is a problem that needs to be solved.

**Comment by jsonin** [comment] 2024-10-16 23:47
I keep thinking everyone can read my mind (and remember every damn post I've made on fillz).

**Open-ended fill as in whatever cells are visible on the screen now**, it's filled. Not for All Time. ;)
This exact feature has worked wonders in fast filling out of a plan (across about 1,000 people testing + using this feature over 18 months).

**Comment by fermion** [comment] 2024-10-16 23:49
> I keep thinking everyone can read my mind (and remember every damn post I've made on fillz).
> 
> **Open-ended fill as in whatever cells are visible on the screen now**, it's filled. Not for All Time. ;) This exact feature has worked wonders in fast filling out of a plan (across about 500 people testing + using this feature over 18 months).

Context, @jsonin 😆 🚀 I do think that there's a use case for a special type of assignment, but we can cross that bridge when we need it.

**Comment by fermion** [comment] 2024-10-16 23:53
@HankC138 @zhukovdigital for now is it possible to look into why the fill forward arrow isn't functional? The expectation here is:

1. fill forward button sets the estimated/planned hours in the current cell until
    * the end of the assignment if an end date exists
    * until the end of the inputs currently in the viewport
2. filling forward with an empty cell or 0 should clear out the values

@ericbenwa @jsonin what do you think about adding a tooltip or some other UI treatment to the work week that's the end date of the assignment if one exists?

**Comment by dreeves4321** [comment] 2024-10-17 00:15
I think theres agreement on open ended projects. But there’s a little misunderstanding here for closed ended. Rob and Corbin raised the issue of filling to the end of assignment when the end of project is not the same date. Juhan repeatedly has mentioned the end of project, but has not answered the question of assignments. I still maintain that the fill should go to end of project, and if necessary change assignment to match. This problem is arising because folks change a project end date without changing assignment end dates. We initially designed that assignments should extend with the project, and autofill as you extend the assignment, but that’s not happening. We could resurrect that solution if preferred. But extending an assignment to fill the project must be a simple one click action. On Oct 16, 2024, at 7:54 PM, Rob Sterner ***@***.***> wrote:﻿
@HankC138 @zhukovdigital for now is it possible to look into why the fill forward arrow isn't functional? The expectation here is:

fill forward button sets the estimated/planned hours in the current cell until

the end of the assignment if an end date exists
until the end of the inputs currently in the viewport


filling forward with an empty cell or 0 should clear out the values

@ericbenwa @jsonin what do you think about adding a tooltip or some other UI treatment to the work week that's the end date of the assignment if one exists?

**Comment by ericbenwa** [comment] 2024-12-11 17:56
Closing this.
I think we've resolved the bugs.
But also want to allow the autofill towards the end date if a project has an end date (and is offscreen).

Recording that specific request here.
https://github.com/goinvo/staffplan-next-app/issues/458

**Closed by ericbenwa** 2024-12-11 17:56 UTC
